### ISSUE TITLE
remove `assign`, `some`, `any`, `keys`

### ISSUE THREAD

**Issue by bekzod** [ember-cli/ember-cli-lodash-subset#34]
since node 4.5 and higher has native support for such utility functions, I think it will be better to remove them

already have corresponding PR's in `ember-cli`
https://github.com/ember-cli/ember-cli/pull/7099 
https://github.com/ember-cli/ember-cli/pull/7100

**Comment by stefanpenner** [comment]
@bekzod I'm good with that, mind submitting a PR for that? We will need to release a major version, but that is fine.

**Comment by bekzod** [comment]
Sure thing

**Comment by btecu** [comment]
This can be closed.
